name: flutterstore
description: A new Flutter ecommerce store application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.0+9

# CCV 1.5 = 1.5.0+9
# CCV 1.4 = 1.4.0+8
# CCV 1.4 = 1.4.0+7
# CCV 1.3 = 1.3.0+6
# CCV 1.2 = 1.2.0+5
# CCV 1.1 = 1.1.0+4
# CCV 1.0 = 1.0.0+3
# CCV 1.0 = 1.0.0+2
# CCV 1.0 = 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.3
#  cached_network_image: 2.1.0+1
#  flutter_cache_manager: 1.2.2 #for cached_network_image
#  http: 0.12.0+4
#  provider: 4.0.5+1
#  connectivity: 0.4.8+2
#  dynamic_theme: 1.0.1
#  sembast: 2.4.3
#  path_provider: 1.6.7
#  intl: 0.16.1
#  shimmer: 1.1.1
  smooth_star_rating: 1.0.4+2
#  url_launcher: 5.4.5
#  carousel_slider: 2.0.0
#  firebase_core: 0.4.4+3
#  firebase_messaging: 6.0.13
#  firebase_auth: 0.16.0 # firebase_auth is for phone login
#  admob_flutter: 0.3.4
#  google_sign_in: 4.4.4
#  flutter_facebook_login: 3.0.0
#  photo_view: 0.9.0
#  flutter_speed_dial: 1.2.5
#  dio: 3.0.9
  image_picker: 0.6.4
#  progress_dialog: 1.2.2
#  braintree_payment: 1.2.4
#  easy_localization: 2.2.1
#  launch_review: 2.0.0
#  package_info: 0.4.0+17
#  flutter_icons: 1.1.0
#  stripe_payment: 1.0.7
#  flutter_credit_card: 0.1.3
#  fluttertoast: 4.0.1
#  permission_handler: 5.0.0+hotfix.4
  

  shared_preferences:
  cached_network_image:
  flutter_cache_manager:  #for cached_network_image
  http:
  provider:
  connectivity:
  dynamic_theme:
  sembast:
  path_provider:
  intl:
  shimmer:
  url_launcher:
  carousel_slider:
  firebase_core:
  firebase_messaging:
  # firebase_auth: 0.16.1 # firebase_auth is for phone login
  flutter_webview_plugin:
  firebase_auth:
  admob_flutter:
  firebase_database:
  google_sign_in:
  flutter_facebook_login:
  photo_view:
  flutter_speed_dial:
  dio:
  progress_dialog:
  braintree_payment:
  easy_localization:
  launch_review:
  package_info:
  flutter_icons:
  stripe_payment:
  flutter_credit_card:
  fluttertoast:
  permission_handler:
  flutter_map:
  latlong:
  geocoder:
  multi_image_picker:
  flutter_widget_from_html:
  esys_flutter_share:
  apple_sign_in:
  razorpay_flutter:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_local_notifications:
  #  path: lib/utils/local_noti/

  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/placeholder_image.png
   - assets/langs/ar-DZ.json
   - assets/langs/en-US.json
   - assets/langs/hi-IN.json
   - assets/langs/de-DE.json
   - assets/langs/es-ES.json
   - assets/langs/fr-FR.json
   - assets/langs/id-ID.json
   - assets/langs/it-IT.json
   - assets/langs/ja-JP.json
   - assets/langs/ko-KR.json
   - assets/langs/ms-MY.json
   - assets/langs/pt-PT.json
   - assets/langs/ru-RU.json
   - assets/langs/th-TH.json
   - assets/langs/tr-TR.json
   - assets/langs/zh-CN.json
   - assets/images/verify_email_icon.jpg
   - assets/images/baseline_feature_circle_24.png
   - assets/images/baesline_access_time_black_24.png
   - assets/images/baseline_check_green_24.png
   - assets/images/baseline_graph_black_24.png
   - assets/images/baseline_price_down_black_24.png
   - assets/images/baseline_price_up_black_24.png
   - assets/images/empty_basket.png
   - assets/images/fs_android_3x.png
   - assets/images/baseline_percent_tag_orange_24.png
   - assets/images/baseline_empty_item_grey_24.png
   - assets/images/home_icon/discount_products.png
   - assets/images/home_icon/easy_payment.png
   - assets/images/home_icon/featured_products.png
   - assets/images/home_icon/free_download.png
   - assets/images/delivery_car_img.png
   - assets/images/trending.png
   



   
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
